/*
 * This C++ program was automatically generated by Genesys 220517 (gowndictator)
 * For your own safety, please review this file before compiling and running it.
 */

#include "kernel/simulator/Simulator.h"
#include "plugins/components/Create.h"
#include "plugins/components/Dispose.h"
#include "plugins/components/DummyComponent.h"

int main(int argc, char** argv) {
	// instantiate simulator
	Simulator* genesys = new Simulator();
	genesys->getTracer()->setTraceLevel(TraceManager::Level::L9_mostDetailed);
	PluginManager* plugins = genesys->getPlugins();
	
	// create model
	Model* model = genesys->getModels()->newModel();
	// model->load("model.gen")
	
	// initialize model parts
	Create* Create_1 = plugins->newInstance<Create>(model, "Create_1");
	DummyComponent* DummyComponent_1 = plugins->newInstance<DummyComponent>(model, "DummyComponent_1");
	Dispose* Dispose_1 = plugins->newInstance<Dispose>(model, "Dispose_1");
	
	// connect model components
	Create_1->getConnectionManager()->insert(DummyComponent_1, 0);
	DummyComponent_1->getConnectionManager()->insert(Dispose_1, 0);
	
	// set simulation parameters
	ModelSimulation* sim = model->getSimulation();
	sim->setNumberOfReplications(1);
	sim->setReplicationLengthTimeUnit(Util::TimeUnit::second);
	sim->setReplicationLength(60.000000);
	sim->setReplicationReportBaseTimeUnit(Util::TimeUnit::second);
	
	// run the simulation
	sim->start();
	
	// free memory
	delete genesys;
	
	return 0;
}
